name: 'R Shiny Apps deploy'
description: 'Deploys your shiny application to shinyapps.io'
inputs:
  r-version:
    description: 'R version to use for the application'
    required: true
    default: '4.0.3'
  shiny_username:
    description: 'Shinyapps.io username'
    required: true
  shiny_token:
    description: 'Shinyapps.io token'
    required: true
  shiny_secret:
    description: 'Shinyapps.io secret'
    required: true
  app_name:
    description: 'Name of the Shiny app'
    required: true
  shiny_path:
    description: 'Path to the Shiny app directory'
    required: true
outputs:
  url:
    description: 'Url to your shiny application'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    - ${{ inputs.r-version }}
    - ${{ inputs.shiny_username }}
    - ${{ inputs.shiny_token }}
    - ${{ inputs.shiny_secret }}
    - ${{ inputs.app_name }}
    - ${{ inputs.app_dir }}
